#!/bin/bash
# A simple bash script to switch a swift '/etc/swift' configuration
# 	- Useful with the swift_perf_test script
#	- Assuming you have test configs installed in SWIFT_TEST_CONFIG_DIR
#
# Author : Sibi Antony, (c) 2012
# sibi [dot] antony [at] gmail [dot] com 

SWIFT_SRC_DIR=~/swift/swift/
SWIFT_CONFIG_DIR="/etc/swift"
SWIFT_TEST_CONFIG_DIR="/etc/swift/swift-test"

if [[ $# -lt 1 ]]; then
	echo "Usage : swift_switch_config {noenc|basic|cdb|dist}"
	exit 1
fi

case "$1" in
	"noenc") echo "noenc" 
		config_dir="noenc"
		;;
	"basic") echo "basic"
		config_dir="basic"
		;;
	"cdb")	echo "cdb"
		config_dir="centrdb"
		;;
	"dist")	echo "dist"
		config_dir="distenc"
		;;
	*)	echo "Wrong choice! {noenc|basic|cdb|dist}"
		exit 1
		;;
esac

# Replace the config
cd ${SWIFT_TEST_CONFIG_DIR}/${config_dir}/
cp proxy-server.conf $SWIFT_CONFIG_DIR/
cp object-server/*.conf $SWIFT_CONFIG_DIR/object-server/

# Reload config
cd $SWIFT_SRC_DIR
python setup.py install
swift-init main restart

